fix: Decrypt predefined keys in build params
cloud-gov/pages-build-container pull request #470
Opened 2024-06-13 21:38 UTC by apburnes

## Changes proposed in this pull request:
- Switches param decryption to just predefined keys in the params
- This work is related to the `4096` character cap on the command passed to a CF task

## security considerations
None

2024-06-13 22:30 UTC, drewbo requested changes

2024-06-13 22:30 UTC, drewbo commented on src/main.py
> +    if any(k in x for x in KEYS_TO_DECRYPT):
`if k in KEYS_TO_DECRYPT`

2024-06-13 22:34 UTC, apburnes commented on src/main.py
> +    if any(k in x for x in KEYS_TO_DECRYPT):
Updated

2024-06-14 22:21 UTC, drewbo approved these changes

2024-06-17 15:24 UTC, merged